[package]
name = "lidp-service"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "OIDC / OAuth 2.x service implementation"

[lib]
name = "lidp_service"

[features]
default = ["std"]
headless = []
std = [
  "key/std",
  "lidp-model/std",
  "model/std",
  "chrono/std",
  "chrono/serde",
  "base64/std",
  "getrandom/std",
  "serde/std",
  "serde_json/std",
  "log/std",
]

[dependencies]
# Internal
db = { path = "../db", default-features = false, features = [] }
key = { path = "../key", default-features = false, features = [] }
model = { path = "../model", default-features = false, features = [] }
lidp-model = { path = "../lidp-model", default-features = false, features = [] }

# Database
libsql = { version = "0.9", default-features = false, features = [
  "core",
  "serde",
] }

# Cryptography
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }
sha2 = { version = "0.10", default-features = false, features = [] }

# Encoding
base64 = { version = "0.22", default-features = false, features = [] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }

# Random
getrandom = { version = "0.3", default-features = false, features = [] }

# Utilities
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "serde",
] }
rust-argon2 = { version = "3.0", default-features = false }
zeroize = { version = "1.9", default-features = false, features = [] }
thiserror = { version = "2.0", default-features = false, features = [] }
config = { version = "0.15", features = ["yaml"], default-features = false }

# Keyring
keyring-core = { version = "1.0", default-features = false, features = [] }

# Logging
log = { version = "0.4", default-features = false, features = [] }
env_logger = { version = "0.10", default-features = false, features = [] }

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = { version = "1.0", default-features = false, features = [] }
dbus-secret-service-keyring-store = { version = "1.0", default-features = false, features = ["crypto-rust"] }

# Windows-only dependency
[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = { version = "1.0", default-features = false, features = [] }

# macOS-only dependency
[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store  = { version = "1.0", default-features = false, features = ["keychain", "protected"] }

# Android-only dependency
[target.'cfg(target_os = "android")'.dependencies]
android-native-keyring-store = { version = "1.0", default-features = false, features = [] }

[dev-dependencies]
tokio = { version = "1.4", default-features = false, features = [
  "macros",
  "rt",
] }
