services:
  libsql:
    container_name: libsql
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
      - SQLD_AUTH_JWT_KEY_FILE=/home/.ssh/libsql.pub
    volumes:
      - libsql:/var/lib/sqld:rw
      - ./keys/libsql.pub:/home/.ssh/libsql.pub:ro

volumes:
  libsql:
    driver: local
