packages:
  - "apps/*"
  - "packages/*"
  - "packages/**/example"
  - "crates/iroh-client-wasm"
  - "crates/tauri-plugin-fetch-api"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@aicacia/svelte-forms@0.1.1'
