/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime.js";
import type {
    ApplicationResponse,
    ClientRegistration,
    CreateApplicationRequest,
    CreatePermissionRequest,
    CreateRoleRequest,
    HealthResponse,
    JwkPublic,
    ManagementKey,
    PermissionResponse,
    RoleResponse,
    UpdateApplicationRequest,
    UserApplicationRoleResponse,
    UserConsentResponse,
    UserInfo,
    VersionResponse,
} from "../models/index.js";
import {
    ApplicationResponseFromJSON,
    ApplicationResponseToJSON,
    ClientRegistrationFromJSON,
    ClientRegistrationToJSON,
    CreateApplicationRequestFromJSON,
    CreateApplicationRequestToJSON,
    CreatePermissionRequestFromJSON,
    CreatePermissionRequestToJSON,
    CreateRoleRequestFromJSON,
    CreateRoleRequestToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
    JwkPublicFromJSON,
    JwkPublicToJSON,
    ManagementKeyFromJSON,
    ManagementKeyToJSON,
    PermissionResponseFromJSON,
    PermissionResponseToJSON,
    RoleResponseFromJSON,
    RoleResponseToJSON,
    UpdateApplicationRequestFromJSON,
    UpdateApplicationRequestToJSON,
    UserApplicationRoleResponseFromJSON,
    UserApplicationRoleResponseToJSON,
    UserConsentResponseFromJSON,
    UserConsentResponseToJSON,
    UserInfoFromJSON,
    UserInfoToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from "../models/index.js";

export interface AssignPermissionToRoleRequest {
    applicationId: string;
    roleId: number;
    permissionId: number;
}

export interface AssignRoleToUserRequest {
    applicationId: string;
    userId: number;
    roleId: number;
}

export interface CreateApplicationOperationRequest {
    createApplicationRequest: CreateApplicationRequest;
}

export interface CreateClientRequest {
    clientRegistration: ClientRegistration;
}

export interface CreatePermissionOperationRequest {
    applicationId: string;
    createPermissionRequest: CreatePermissionRequest;
}

export interface CreateRoleOperationRequest {
    applicationId: string;
    createRoleRequest: CreateRoleRequest;
}

export interface DeleteApplicationRequest {
    applicationId: string;
}

export interface DeleteClientRequest {
    clientId: string;
}

export interface DeletePermissionRequest {
    applicationId: string;
    permissionId: number;
}

export interface DeleteRoleRequest {
    applicationId: string;
    roleId: number;
}

export interface GetApplicationRequest {
    applicationId: string;
}

export interface GetClientRequest {
    clientId: string;
}

export interface GetKeyJwkRequest {
    keyId: number;
}

export interface GetUserRequest {
    userId: number;
}

export interface ListApplicationsRequest {
    offset: number;
    limit: number;
}

export interface ListClientKeysRequest {
    clientId: string;
}

export interface ListClientsRequest {
    offset: number;
    limit: number;
}

export interface ListPermissionsRequest {
    applicationId: string;
    offset: number;
    limit: number;
}

export interface ListRolePermissionsRequest {
    applicationId: string;
    roleId: number;
}

export interface ListRolesRequest {
    applicationId: string;
    offset: number;
    limit: number;
}

export interface ListUserConsentsRequest {
    userId: number;
    offset: number;
    limit: number;
}

export interface ListUserRolesRequest {
    applicationId: string;
    userId: number;
}

export interface ListUserRolesAcrossApplicationsRequest {
    userId: number;
}

export interface ListUsersRequest {
    offset: number;
    limit: number;
}

export interface RevokePermissionFromRoleRequest {
    applicationId: string;
    roleId: number;
    permissionId: number;
}

export interface RevokeRoleFromUserRequest {
    applicationId: string;
    userId: number;
    roleId: number;
}

export interface RevokeUserConsentRequest {
    userId: number;
    consentId: number;
}

export interface UpdateApplicationOperationRequest {
    applicationId: string;
    updateApplicationRequest: UpdateApplicationRequest;
}

export interface UpdateClientRequest {
    clientId: string;
    clientRegistration: ClientRegistration;
}

/**
 * DefaultApi - interface
 *
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} roleId Role ID
     * @param {number} permissionId Permission ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    assignPermissionToRoleRaw(
        requestParameters: AssignPermissionToRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    assignPermissionToRole(
        requestParameters: AssignPermissionToRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} userId User ID
     * @param {number} roleId Role ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    assignRoleToUserRaw(
        requestParameters: AssignRoleToUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    assignRoleToUser(
        requestParameters: AssignRoleToUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {CreateApplicationRequest} createApplicationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createApplicationRaw(
        requestParameters: CreateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>>;

    /**
     */
    createApplication(
        requestParameters: CreateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse>;

    /**
     *
     * @param {ClientRegistration} clientRegistration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createClientRaw(
        requestParameters: CreateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    createClient(
        requestParameters: CreateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {CreatePermissionRequest} createPermissionRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPermissionRaw(
        requestParameters: CreatePermissionOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PermissionResponse>>;

    /**
     */
    createPermission(
        requestParameters: CreatePermissionOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PermissionResponse>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {CreateRoleRequest} createRoleRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createRoleRaw(
        requestParameters: CreateRoleOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RoleResponse>>;

    /**
     */
    createRole(
        requestParameters: CreateRoleOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RoleResponse>;

    /**
     *
     * @param {string} applicationId Application ID (URI)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteApplicationRaw(
        requestParameters: DeleteApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteApplication(
        requestParameters: DeleteApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} clientId Client ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteClientRaw(
        requestParameters: DeleteClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteClient(
        requestParameters: DeleteClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} permissionId Permission ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deletePermissionRaw(
        requestParameters: DeletePermissionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deletePermission(
        requestParameters: DeletePermissionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} roleId Role ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteRoleRaw(
        requestParameters: DeleteRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteRole(
        requestParameters: DeleteRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID (URI)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getApplicationRaw(
        requestParameters: GetApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>>;

    /**
     */
    getApplication(
        requestParameters: GetApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse>;

    /**
     *
     * @param {string} clientId Client ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getClientRaw(
        requestParameters: GetClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    getClient(
        requestParameters: GetClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration>;

    /**
     *
     * @param {number} keyId Key ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getKeyJwkRaw(
        requestParameters: GetKeyJwkRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<JwkPublic>>;

    /**
     */
    getKeyJwk(
        requestParameters: GetKeyJwkRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<JwkPublic>;

    /**
     *
     * @param {number} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUserRaw(
        requestParameters: GetUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<UserInfo>>;

    /**
     */
    getUser(
        requestParameters: GetUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<UserInfo>;

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    healthRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<HealthResponse>>;

    /**
     */
    health(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<HealthResponse>;

    /**
     *
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listApplicationsRaw(
        requestParameters: ListApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ApplicationResponse>>>;

    /**
     */
    listApplications(
        requestParameters: ListApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ApplicationResponse>>;

    /**
     *
     * @param {string} clientId Client ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listClientKeysRaw(
        requestParameters: ListClientKeysRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ManagementKey>>>;

    /**
     */
    listClientKeys(
        requestParameters: ListClientKeysRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ManagementKey>>;

    /**
     *
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listClientsRaw(
        requestParameters: ListClientsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ClientRegistration>>>;

    /**
     */
    listClients(
        requestParameters: ListClientsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ClientRegistration>>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPermissionsRaw(
        requestParameters: ListPermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<PermissionResponse>>>;

    /**
     */
    listPermissions(
        requestParameters: ListPermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<PermissionResponse>>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} roleId Role ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listRolePermissionsRaw(
        requestParameters: ListRolePermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<PermissionResponse>>>;

    /**
     */
    listRolePermissions(
        requestParameters: ListRolePermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<PermissionResponse>>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listRolesRaw(
        requestParameters: ListRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<RoleResponse>>>;

    /**
     */
    listRoles(
        requestParameters: ListRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<RoleResponse>>;

    /**
     *
     * @param {number} userId User ID
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listUserConsentsRaw(
        requestParameters: ListUserConsentsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserConsentResponse>>>;

    /**
     */
    listUserConsents(
        requestParameters: ListUserConsentsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserConsentResponse>>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listUserRolesRaw(
        requestParameters: ListUserRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<RoleResponse>>>;

    /**
     */
    listUserRoles(
        requestParameters: ListUserRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<RoleResponse>>;

    /**
     *
     * @param {number} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listUserRolesAcrossApplicationsRaw(
        requestParameters: ListUserRolesAcrossApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserApplicationRoleResponse>>>;

    /**
     */
    listUserRolesAcrossApplications(
        requestParameters: ListUserRolesAcrossApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserApplicationRoleResponse>>;

    /**
     *
     * @param {number} offset
     * @param {number} limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listUsersRaw(
        requestParameters: ListUsersRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserInfo>>>;

    /**
     */
    listUsers(
        requestParameters: ListUsersRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserInfo>>;

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    openapiJsonRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    openapiJson(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} roleId Role ID
     * @param {number} permissionId Permission ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    revokePermissionFromRoleRaw(
        requestParameters: RevokePermissionFromRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    revokePermissionFromRole(
        requestParameters: RevokePermissionFromRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID
     * @param {number} userId User ID
     * @param {number} roleId Role ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    revokeRoleFromUserRaw(
        requestParameters: RevokeRoleFromUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    revokeRoleFromUser(
        requestParameters: RevokeRoleFromUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {number} userId User ID
     * @param {number} consentId Consent ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    revokeUserConsentRaw(
        requestParameters: RevokeUserConsentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     */
    revokeUserConsent(
        requestParameters: RevokeUserConsentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @param {string} applicationId Application ID (URI)
     * @param {UpdateApplicationRequest} updateApplicationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateApplicationRaw(
        requestParameters: UpdateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>>;

    /**
     */
    updateApplication(
        requestParameters: UpdateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse>;

    /**
     *
     * @param {string} clientId Client ID
     * @param {ClientRegistration} clientRegistration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateClientRaw(
        requestParameters: UpdateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    updateClient(
        requestParameters: UpdateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration>;

    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    versionRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<VersionResponse>>;

    /**
     */
    version(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<VersionResponse>;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {
    /**
     */
    async assignPermissionToRoleRaw(
        requestParameters: AssignPermissionToRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling assignPermissionToRole().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling assignPermissionToRole().',
            );
        }

        if (requestParameters["permissionId"] == null) {
            throw new runtime.RequiredError(
                "permissionId",
                'Required parameter "permissionId" was null or undefined when calling assignPermissionToRole().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles/{role_id}/permissions/{permission_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );
        urlPath = urlPath.replace(
            `{${"permission_id"}}`,
            encodeURIComponent(String(requestParameters["permissionId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assignPermissionToRole(
        requestParameters: AssignPermissionToRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.assignPermissionToRoleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assignRoleToUserRaw(
        requestParameters: AssignRoleToUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling assignRoleToUser().',
            );
        }

        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling assignRoleToUser().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling assignRoleToUser().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/users/{user_id}/roles/{role_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assignRoleToUser(
        requestParameters: AssignRoleToUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.assignRoleToUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createApplicationRaw(
        requestParameters: CreateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>> {
        if (requestParameters["createApplicationRequest"] == null) {
            throw new runtime.RequiredError(
                "createApplicationRequest",
                'Required parameter "createApplicationRequest" was null or undefined when calling createApplication().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: CreateApplicationRequestToJSON(
                    requestParameters["createApplicationRequest"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ApplicationResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async createApplication(
        requestParameters: CreateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse> {
        const response = await this.createApplicationRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async createClientRaw(
        requestParameters: CreateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters["clientRegistration"] == null) {
            throw new runtime.RequiredError(
                "clientRegistration",
                'Required parameter "clientRegistration" was null or undefined when calling createClient().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients`;

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: ClientRegistrationToJSON(
                    requestParameters["clientRegistration"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ClientRegistrationFromJSON(jsonValue),
        );
    }

    /**
     */
    async createClient(
        requestParameters: CreateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration> {
        const response = await this.createClientRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async createPermissionRaw(
        requestParameters: CreatePermissionOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<PermissionResponse>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling createPermission().',
            );
        }

        if (requestParameters["createPermissionRequest"] == null) {
            throw new runtime.RequiredError(
                "createPermissionRequest",
                'Required parameter "createPermissionRequest" was null or undefined when calling createPermission().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/permissions`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: CreatePermissionRequestToJSON(
                    requestParameters["createPermissionRequest"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            PermissionResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async createPermission(
        requestParameters: CreatePermissionOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<PermissionResponse> {
        const response = await this.createPermissionRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async createRoleRaw(
        requestParameters: CreateRoleOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<RoleResponse>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling createRole().',
            );
        }

        if (requestParameters["createRoleRequest"] == null) {
            throw new runtime.RequiredError(
                "createRoleRequest",
                'Required parameter "createRoleRequest" was null or undefined when calling createRole().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: CreateRoleRequestToJSON(
                    requestParameters["createRoleRequest"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            RoleResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async createRole(
        requestParameters: CreateRoleOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<RoleResponse> {
        const response = await this.createRoleRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async deleteApplicationRaw(
        requestParameters: DeleteApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling deleteApplication().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteApplication(
        requestParameters: DeleteApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.deleteApplicationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteClientRaw(
        requestParameters: DeleteClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["clientId"] == null) {
            throw new runtime.RequiredError(
                "clientId",
                'Required parameter "clientId" was null or undefined when calling deleteClient().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients/{client_id}`;
        urlPath = urlPath.replace(
            `{${"client_id"}}`,
            encodeURIComponent(String(requestParameters["clientId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteClient(
        requestParameters: DeleteClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.deleteClientRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deletePermissionRaw(
        requestParameters: DeletePermissionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling deletePermission().',
            );
        }

        if (requestParameters["permissionId"] == null) {
            throw new runtime.RequiredError(
                "permissionId",
                'Required parameter "permissionId" was null or undefined when calling deletePermission().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/permissions/{permission_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"permission_id"}}`,
            encodeURIComponent(String(requestParameters["permissionId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deletePermission(
        requestParameters: DeletePermissionRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.deletePermissionRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteRoleRaw(
        requestParameters: DeleteRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling deleteRole().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling deleteRole().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles/{role_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteRole(
        requestParameters: DeleteRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.deleteRoleRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getApplicationRaw(
        requestParameters: GetApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling getApplication().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ApplicationResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async getApplication(
        requestParameters: GetApplicationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse> {
        const response = await this.getApplicationRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async getClientRaw(
        requestParameters: GetClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters["clientId"] == null) {
            throw new runtime.RequiredError(
                "clientId",
                'Required parameter "clientId" was null or undefined when calling getClient().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients/{client_id}`;
        urlPath = urlPath.replace(
            `{${"client_id"}}`,
            encodeURIComponent(String(requestParameters["clientId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ClientRegistrationFromJSON(jsonValue),
        );
    }

    /**
     */
    async getClient(
        requestParameters: GetClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration> {
        const response = await this.getClientRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async getKeyJwkRaw(
        requestParameters: GetKeyJwkRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<JwkPublic>> {
        if (requestParameters["keyId"] == null) {
            throw new runtime.RequiredError(
                "keyId",
                'Required parameter "keyId" was null or undefined when calling getKeyJwk().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/keys/{key_id}/jwk`;
        urlPath = urlPath.replace(
            `{${"key_id"}}`,
            encodeURIComponent(String(requestParameters["keyId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            JwkPublicFromJSON(jsonValue),
        );
    }

    /**
     */
    async getKeyJwk(
        requestParameters: GetKeyJwkRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<JwkPublic> {
        const response = await this.getKeyJwkRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async getUserRaw(
        requestParameters: GetUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<UserInfo>> {
        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling getUser().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{user_id}`;
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            UserInfoFromJSON(jsonValue),
        );
    }

    /**
     */
    async getUser(
        requestParameters: GetUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<UserInfo> {
        const response = await this.getUserRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async healthRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/health`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            HealthResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async health(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<HealthResponse> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async listApplicationsRaw(
        requestParameters: ListApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ApplicationResponse>>> {
        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listApplications().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listApplications().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications`;
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(ApplicationResponseFromJSON),
        );
    }

    /**
     */
    async listApplications(
        requestParameters: ListApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ApplicationResponse>> {
        const response = await this.listApplicationsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listClientKeysRaw(
        requestParameters: ListClientKeysRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ManagementKey>>> {
        if (requestParameters["clientId"] == null) {
            throw new runtime.RequiredError(
                "clientId",
                'Required parameter "clientId" was null or undefined when calling listClientKeys().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients/{client_id}/keys`;
        urlPath = urlPath.replace(
            `{${"client_id"}}`,
            encodeURIComponent(String(requestParameters["clientId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(ManagementKeyFromJSON),
        );
    }

    /**
     */
    async listClientKeys(
        requestParameters: ListClientKeysRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ManagementKey>> {
        const response = await this.listClientKeysRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listClientsRaw(
        requestParameters: ListClientsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<ClientRegistration>>> {
        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listClients().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listClients().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients`;
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(ClientRegistrationFromJSON),
        );
    }

    /**
     */
    async listClients(
        requestParameters: ListClientsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<ClientRegistration>> {
        const response = await this.listClientsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listPermissionsRaw(
        requestParameters: ListPermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<PermissionResponse>>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling listPermissions().',
            );
        }

        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listPermissions().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listPermissions().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/permissions`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(PermissionResponseFromJSON),
        );
    }

    /**
     */
    async listPermissions(
        requestParameters: ListPermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<PermissionResponse>> {
        const response = await this.listPermissionsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listRolePermissionsRaw(
        requestParameters: ListRolePermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<PermissionResponse>>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling listRolePermissions().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling listRolePermissions().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles/{role_id}/permissions`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(PermissionResponseFromJSON),
        );
    }

    /**
     */
    async listRolePermissions(
        requestParameters: ListRolePermissionsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<PermissionResponse>> {
        const response = await this.listRolePermissionsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listRolesRaw(
        requestParameters: ListRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<RoleResponse>>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling listRoles().',
            );
        }

        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listRoles().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listRoles().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(RoleResponseFromJSON),
        );
    }

    /**
     */
    async listRoles(
        requestParameters: ListRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<RoleResponse>> {
        const response = await this.listRolesRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listUserConsentsRaw(
        requestParameters: ListUserConsentsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserConsentResponse>>> {
        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling listUserConsents().',
            );
        }

        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listUserConsents().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listUserConsents().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{user_id}/consents`;
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(UserConsentResponseFromJSON),
        );
    }

    /**
     */
    async listUserConsents(
        requestParameters: ListUserConsentsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserConsentResponse>> {
        const response = await this.listUserConsentsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listUserRolesRaw(
        requestParameters: ListUserRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<RoleResponse>>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling listUserRoles().',
            );
        }

        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling listUserRoles().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/users/{user_id}/roles`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(RoleResponseFromJSON),
        );
    }

    /**
     */
    async listUserRoles(
        requestParameters: ListUserRolesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<RoleResponse>> {
        const response = await this.listUserRolesRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listUserRolesAcrossApplicationsRaw(
        requestParameters: ListUserRolesAcrossApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserApplicationRoleResponse>>> {
        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling listUserRolesAcrossApplications().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{user_id}/roles`;
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(UserApplicationRoleResponseFromJSON),
        );
    }

    /**
     */
    async listUserRolesAcrossApplications(
        requestParameters: ListUserRolesAcrossApplicationsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserApplicationRoleResponse>> {
        const response = await this.listUserRolesAcrossApplicationsRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async listUsersRaw(
        requestParameters: ListUsersRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<UserInfo>>> {
        if (requestParameters["offset"] == null) {
            throw new runtime.RequiredError(
                "offset",
                'Required parameter "offset" was null or undefined when calling listUsers().',
            );
        }

        if (requestParameters["limit"] == null) {
            throw new runtime.RequiredError(
                "limit",
                'Required parameter "limit" was null or undefined when calling listUsers().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users`;
        urlPath = urlPath.replace(
            `{${"offset"}}`,
            encodeURIComponent(String(requestParameters["offset"])),
        );
        urlPath = urlPath.replace(
            `{${"limit"}}`,
            encodeURIComponent(String(requestParameters["limit"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            jsonValue.map(UserInfoFromJSON),
        );
    }

    /**
     */
    async listUsers(
        requestParameters: ListUsersRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<UserInfo>> {
        const response = await this.listUsersRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async openapiJsonRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/openapi.json`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async openapiJson(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.openapiJsonRaw(initOverrides);
    }

    /**
     */
    async revokePermissionFromRoleRaw(
        requestParameters: RevokePermissionFromRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling revokePermissionFromRole().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling revokePermissionFromRole().',
            );
        }

        if (requestParameters["permissionId"] == null) {
            throw new runtime.RequiredError(
                "permissionId",
                'Required parameter "permissionId" was null or undefined when calling revokePermissionFromRole().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/roles/{role_id}/permissions/{permission_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );
        urlPath = urlPath.replace(
            `{${"permission_id"}}`,
            encodeURIComponent(String(requestParameters["permissionId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokePermissionFromRole(
        requestParameters: RevokePermissionFromRoleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.revokePermissionFromRoleRaw(
            requestParameters,
            initOverrides,
        );
    }

    /**
     */
    async revokeRoleFromUserRaw(
        requestParameters: RevokeRoleFromUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling revokeRoleFromUser().',
            );
        }

        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling revokeRoleFromUser().',
            );
        }

        if (requestParameters["roleId"] == null) {
            throw new runtime.RequiredError(
                "roleId",
                'Required parameter "roleId" was null or undefined when calling revokeRoleFromUser().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}/users/{user_id}/roles/{role_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );
        urlPath = urlPath.replace(
            `{${"role_id"}}`,
            encodeURIComponent(String(requestParameters["roleId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokeRoleFromUser(
        requestParameters: RevokeRoleFromUserRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.revokeRoleFromUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async revokeUserConsentRaw(
        requestParameters: RevokeUserConsentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling revokeUserConsent().',
            );
        }

        if (requestParameters["consentId"] == null) {
            throw new runtime.RequiredError(
                "consentId",
                'Required parameter "consentId" was null or undefined when calling revokeUserConsent().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{user_id}/consents/{consent_id}`;
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"])),
        );
        urlPath = urlPath.replace(
            `{${"consent_id"}}`,
            encodeURIComponent(String(requestParameters["consentId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revokeUserConsent(
        requestParameters: RevokeUserConsentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.revokeUserConsentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateApplicationRaw(
        requestParameters: UpdateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ApplicationResponse>> {
        if (requestParameters["applicationId"] == null) {
            throw new runtime.RequiredError(
                "applicationId",
                'Required parameter "applicationId" was null or undefined when calling updateApplication().',
            );
        }

        if (requestParameters["updateApplicationRequest"] == null) {
            throw new runtime.RequiredError(
                "updateApplicationRequest",
                'Required parameter "updateApplicationRequest" was null or undefined when calling updateApplication().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/applications/{application_id}`;
        urlPath = urlPath.replace(
            `{${"application_id"}}`,
            encodeURIComponent(String(requestParameters["applicationId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: UpdateApplicationRequestToJSON(
                    requestParameters["updateApplicationRequest"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ApplicationResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async updateApplication(
        requestParameters: UpdateApplicationOperationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ApplicationResponse> {
        const response = await this.updateApplicationRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async updateClientRaw(
        requestParameters: UpdateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters["clientId"] == null) {
            throw new runtime.RequiredError(
                "clientId",
                'Required parameter "clientId" was null or undefined when calling updateClient().',
            );
        }

        if (requestParameters["clientRegistration"] == null) {
            throw new runtime.RequiredError(
                "clientRegistration",
                'Required parameter "clientRegistration" was null or undefined when calling updateClient().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/clients/{client_id}`;
        urlPath = urlPath.replace(
            `{${"client_id"}}`,
            encodeURIComponent(String(requestParameters["clientId"])),
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "PUT",
                headers: headerParameters,
                query: queryParameters,
                body: ClientRegistrationToJSON(
                    requestParameters["clientRegistration"],
                ),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ClientRegistrationFromJSON(jsonValue),
        );
    }

    /**
     */
    async updateClient(
        requestParameters: UpdateClientRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<ClientRegistration> {
        const response = await this.updateClientRaw(
            requestParameters,
            initOverrides,
        );
        return await response.value();
    }

    /**
     */
    async versionRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<VersionResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        let urlPath = `/version`;

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            VersionResponseFromJSON(jsonValue),
        );
    }

    /**
     */
    async version(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<VersionResponse> {
        const response = await this.versionRaw(initOverrides);
        return await response.value();
    }
}
