/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AuthorizationServerMetadata,
  ClientRegistration,
  DeviceAuthorization,
  HealthResponse,
  Jwks,
  SubjectTokenType,
  TokenResponse,
  UserInfo,
  VersionResponse,
} from '../models/index.js';
import {
    AuthorizationServerMetadataFromJSON,
    AuthorizationServerMetadataToJSON,
    ClientRegistrationFromJSON,
    ClientRegistrationToJSON,
    DeviceAuthorizationFromJSON,
    DeviceAuthorizationToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
    JwksFromJSON,
    JwksToJSON,
    SubjectTokenTypeFromJSON,
    SubjectTokenTypeToJSON,
    TokenResponseFromJSON,
    TokenResponseToJSON,
    UserInfoFromJSON,
    UserInfoToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index.js';

export interface DeleteRegisterRequest {
    clientId: string;
}

export interface DeviceAuthRequest {
    clientId?: string | null;
    scope?: string | null;
}

export interface GetRegisterRequest {
    clientId: string;
}

export interface PutRegisterRequest {
    clientId: string;
    clientRegistration: ClientRegistration;
}

export interface RegisterRequest {
    clientRegistration: ClientRegistration;
}

export interface RevokeRequest {
    token: string;
    tokenTypeHint?: string | null;
}

export interface TokenRequest {
    clientId?: string;
    password?: string;
    resource?: string | null;
    scope?: string | null;
    username?: string;
    grantType?: TokenGrantTypeEnum;
    code?: string;
    codeVerifier?: string;
    redirectUri?: string | null;
    audience?: string | null;
    clientSecret?: string;
    refreshToken?: string;
    actorToken?: string | null;
    actorTokenType?: string | null;
    requestedTokenType?: string | null;
    subjectToken?: string;
    subjectTokenType?: SubjectTokenType;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    authorizeJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authorizeJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    authorizeQueryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authorizeQuery(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} clientId Client ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteRegisterRaw(requestParameters: DeleteRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteRegister(requestParameters: DeleteRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} [clientId] 
     * @param {string} [scope] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deviceAuthRaw(requestParameters: DeviceAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceAuthorization>>;

    /**
     */
    deviceAuth(requestParameters: DeviceAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceAuthorization>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deviceVerifyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deviceVerify(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} clientId Client ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRegisterRaw(requestParameters: GetRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    getRegister(requestParameters: GetRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>>;

    /**
     */
    health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    jwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Jwks>>;

    /**
     */
    jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Jwks>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    openapiJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    openapiJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    openidConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthorizationServerMetadata>>;

    /**
     */
    openidConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthorizationServerMetadata>;

    /**
     * 
     * @param {string} clientId Client ID
     * @param {ClientRegistration} clientRegistration 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    putRegisterRaw(requestParameters: PutRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    putRegister(requestParameters: PutRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration>;

    /**
     * 
     * @param {ClientRegistration} clientRegistration 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>>;

    /**
     */
    register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration>;

    /**
     * 
     * @param {string} token 
     * @param {string} [tokenTypeHint] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    revokeRaw(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    revoke(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    sessionsLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    sessionsLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} [clientId] 
     * @param {string} [password] 
     * @param {string} [resource] 
     * @param {string} [scope] 
     * @param {string} [username] 
     * @param {string} [grantType] 
     * @param {string} [code] The authorization code received from the authorization server.
     * @param {string} [codeVerifier] PKCE parameters (if the client used PKCE during the authorization request)
     * @param {string} [redirectUri] 
     * @param {string} [audience] 
     * @param {string} [clientSecret] 
     * @param {string} [refreshToken] 
     * @param {string} [actorToken] 
     * @param {string} [actorTokenType] 
     * @param {string} [requestedTokenType] 
     * @param {string} [subjectToken] 
     * @param {SubjectTokenType} [subjectTokenType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     */
    token(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    userinfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfo>>;

    /**
     */
    userinfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    versionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionResponse>>;

    /**
     */
    version(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionResponse>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     */
    async authorizeJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authorizeJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authorizeJsonRaw(initOverrides);
    }

    /**
     */
    async authorizeQueryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authorizeQuery(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authorizeQueryRaw(initOverrides);
    }

    /**
     */
    async deleteRegisterRaw(requestParameters: DeleteRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling deleteRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/register/{client_id}`;
        urlPath = urlPath.replace(`{${"client_id"}}`, encodeURIComponent(String(requestParameters['clientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteRegister(requestParameters: DeleteRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRegisterRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deviceAuthRaw(requestParameters: DeviceAuthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceAuthorization>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }


        let urlPath = `/oauth2/device/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceAuthorizationFromJSON(jsonValue));
    }

    /**
     */
    async deviceAuth(requestParameters: DeviceAuthRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceAuthorization> {
        const response = await this.deviceAuthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deviceVerifyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/device/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deviceVerify(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deviceVerifyRaw(initOverrides);
    }

    /**
     */
    async getRegisterRaw(requestParameters: GetRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling getRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/register/{client_id}`;
        urlPath = urlPath.replace(`{${"client_id"}}`, encodeURIComponent(String(requestParameters['clientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientRegistrationFromJSON(jsonValue));
    }

    /**
     */
    async getRegister(requestParameters: GetRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration> {
        const response = await this.getRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async jwksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Jwks>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/.well-known/jwks.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwksFromJSON(jsonValue));
    }

    /**
     */
    async jwks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Jwks> {
        const response = await this.jwksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async openapiJsonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/openapi.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async openapiJson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.openapiJsonRaw(initOverrides);
    }

    /**
     */
    async openidConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthorizationServerMetadata>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/.well-known/openid-configuration`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorizationServerMetadataFromJSON(jsonValue));
    }

    /**
     */
    async openidConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthorizationServerMetadata> {
        const response = await this.openidConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async putRegisterRaw(requestParameters: PutRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling putRegister().'
            );
        }

        if (requestParameters['clientRegistration'] == null) {
            throw new runtime.RequiredError(
                'clientRegistration',
                'Required parameter "clientRegistration" was null or undefined when calling putRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/oauth2/register/{client_id}`;
        urlPath = urlPath.replace(`{${"client_id"}}`, encodeURIComponent(String(requestParameters['clientId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ClientRegistrationToJSON(requestParameters['clientRegistration']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientRegistrationFromJSON(jsonValue));
    }

    /**
     */
    async putRegister(requestParameters: PutRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration> {
        const response = await this.putRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientRegistration>> {
        if (requestParameters['clientRegistration'] == null) {
            throw new runtime.RequiredError(
                'clientRegistration',
                'Required parameter "clientRegistration" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/oauth2/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClientRegistrationToJSON(requestParameters['clientRegistration']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientRegistrationFromJSON(jsonValue));
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientRegistration> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async revokeRaw(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling revoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['token'] != null) {
            formParams.append('token', requestParameters['token'] as any);
        }

        if (requestParameters['tokenTypeHint'] != null) {
            formParams.append('token_type_hint', requestParameters['tokenTypeHint'] as any);
        }


        let urlPath = `/oauth2/revoke`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async revoke(requestParameters: RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async sessionsLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/sessions/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async sessionsLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessionsLogoutRaw(initOverrides);
    }

    /**
     */
    async tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['resource'] != null) {
            formParams.append('resource', requestParameters['resource'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }

        if (requestParameters['codeVerifier'] != null) {
            formParams.append('code_verifier', requestParameters['codeVerifier'] as any);
        }

        if (requestParameters['redirectUri'] != null) {
            formParams.append('redirect_uri', requestParameters['redirectUri'] as any);
        }

        if (requestParameters['audience'] != null) {
            formParams.append('audience', requestParameters['audience'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('client_secret', requestParameters['clientSecret'] as any);
        }

        if (requestParameters['refreshToken'] != null) {
            formParams.append('refresh_token', requestParameters['refreshToken'] as any);
        }

        if (requestParameters['actorToken'] != null) {
            formParams.append('actor_token', requestParameters['actorToken'] as any);
        }

        if (requestParameters['actorTokenType'] != null) {
            formParams.append('actor_token_type', requestParameters['actorTokenType'] as any);
        }

        if (requestParameters['requestedTokenType'] != null) {
            formParams.append('requested_token_type', requestParameters['requestedTokenType'] as any);
        }

        if (requestParameters['subjectToken'] != null) {
            formParams.append('subject_token', requestParameters['subjectToken'] as any);
        }

        if (requestParameters['subjectTokenType'] != null) {
            formParams.append('subject_token_type', requestParameters['subjectTokenType'] as any);
        }


        let urlPath = `/oauth2/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async token(requestParameters: TokenRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.tokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userinfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/userinfo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoFromJSON(jsonValue));
    }

    /**
     */
    async userinfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo> {
        const response = await this.userinfoRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async versionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/version`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionResponseFromJSON(jsonValue));
    }

    /**
     */
    async version(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionResponse> {
        const response = await this.versionRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const TokenGrantTypeEnum = {
    UrnIetfParamsOauthGrantTypeTokenExchange: 'urn:ietf:params:oauth:grant-type:token-exchange'
} as const;
export type TokenGrantTypeEnum = typeof TokenGrantTypeEnum[keyof typeof TokenGrantTypeEnum];
