[package]
name = "storage-model"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Storage bridge authentication and authorization models"

[lib]
name = "storage_model"

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "chrono/std", "lidp-model/std"]
migrate = ["dep:db", "dep:include_dir"]

[dependencies]
# Internal
lidp-model = { path = "../lidp-model", default-features = false, features = [] }
db = { path = "../db", default-features = false, features = ["migrate"], optional = true }
libsql = { version = "0.9", default-features = false, features = [] }

# Serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = [] }

# Utilities
chrono = { version = "0.4", default-features = false, features = ["serde", "alloc"] }
include_dir = { version = "0.7", default-features = false, features = [], optional = true }
