/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface ApplicationResponse
 */
export interface ApplicationResponse {
    /**
     *
     * @type {number}
     * @memberof ApplicationResponse
     */
    createdAt: number;
    /**
     *
     * @type {string}
     * @memberof ApplicationResponse
     */
    description?: string | null;
    /**
     *
     * @type {number}
     * @memberof ApplicationResponse
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof ApplicationResponse
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof ApplicationResponse
     */
    updatedAt: number;
    /**
     *
     * @type {string}
     * @memberof ApplicationResponse
     */
    uri: string;
}

/**
 * Check if a given object implements the ApplicationResponse interface.
 */
export function instanceOfApplicationResponse(
    value: object,
): value is ApplicationResponse {
    if (!("createdAt" in value) || value["createdAt"] === undefined)
        return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    if (!("uri" in value) || value["uri"] === undefined) return false;
    return true;
}

export function ApplicationResponseFromJSON(json: any): ApplicationResponse {
    return ApplicationResponseFromJSONTyped(json, false);
}

export function ApplicationResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ApplicationResponse {
    if (json == null) {
        return json;
    }
    return {
        createdAt: json["created_at"],
        description:
            json["description"] == null ? undefined : json["description"],
        id: json["id"],
        name: json["name"],
        updatedAt: json["updated_at"],
        uri: json["uri"],
    };
}

export function ApplicationResponseToJSON(json: any): ApplicationResponse {
    return ApplicationResponseToJSONTyped(json, false);
}

export function ApplicationResponseToJSONTyped(
    value?: ApplicationResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        created_at: value["createdAt"],
        description: value["description"],
        id: value["id"],
        name: value["name"],
        updated_at: value["updatedAt"],
        uri: value["uri"],
    };
}
