/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface CreatePermissionRequest
 */
export interface CreatePermissionRequest {
    /**
     *
     * @type {string}
     * @memberof CreatePermissionRequest
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof CreatePermissionRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreatePermissionRequest interface.
 */
export function instanceOfCreatePermissionRequest(
    value: object,
): value is CreatePermissionRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function CreatePermissionRequestFromJSON(
    json: any,
): CreatePermissionRequest {
    return CreatePermissionRequestFromJSONTyped(json, false);
}

export function CreatePermissionRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CreatePermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        description:
            json["description"] == null ? undefined : json["description"],
        name: json["name"],
    };
}

export function CreatePermissionRequestToJSON(
    json: any,
): CreatePermissionRequest {
    return CreatePermissionRequestToJSONTyped(json, false);
}

export function CreatePermissionRequestToJSONTyped(
    value?: CreatePermissionRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        name: value["name"],
    };
}
