/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface CreateApplicationRequest
 */
export interface CreateApplicationRequest {
    /**
     *
     * @type {string}
     * @memberof CreateApplicationRequest
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof CreateApplicationRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateApplicationRequest
     */
    uri: string;
}

/**
 * Check if a given object implements the CreateApplicationRequest interface.
 */
export function instanceOfCreateApplicationRequest(
    value: object,
): value is CreateApplicationRequest {
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("uri" in value) || value["uri"] === undefined) return false;
    return true;
}

export function CreateApplicationRequestFromJSON(
    json: any,
): CreateApplicationRequest {
    return CreateApplicationRequestFromJSONTyped(json, false);
}

export function CreateApplicationRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): CreateApplicationRequest {
    if (json == null) {
        return json;
    }
    return {
        description:
            json["description"] == null ? undefined : json["description"],
        name: json["name"],
        uri: json["uri"],
    };
}

export function CreateApplicationRequestToJSON(
    json: any,
): CreateApplicationRequest {
    return CreateApplicationRequestToJSONTyped(json, false);
}

export function CreateApplicationRequestToJSONTyped(
    value?: CreateApplicationRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        name: value["name"],
        uri: value["uri"],
    };
}
