/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface JwkPublicParametersOneOf1
 */
export interface JwkPublicParametersOneOf1 {
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf1
     */
    crv: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf1
     */
    kty: JwkPublicParametersOneOf1KtyEnum;
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf1
     */
    x: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf1
     */
    y: string;
}

/**
 * @export
 */
export const JwkPublicParametersOneOf1KtyEnum = {
    Ec: "Ec",
} as const;
export type JwkPublicParametersOneOf1KtyEnum =
    (typeof JwkPublicParametersOneOf1KtyEnum)[keyof typeof JwkPublicParametersOneOf1KtyEnum];

/**
 * Check if a given object implements the JwkPublicParametersOneOf1 interface.
 */
export function instanceOfJwkPublicParametersOneOf1(
    value: object,
): value is JwkPublicParametersOneOf1 {
    if (!("crv" in value) || value["crv"] === undefined) return false;
    if (!("kty" in value) || value["kty"] === undefined) return false;
    if (!("x" in value) || value["x"] === undefined) return false;
    if (!("y" in value) || value["y"] === undefined) return false;
    return true;
}

export function JwkPublicParametersOneOf1FromJSON(
    json: any,
): JwkPublicParametersOneOf1 {
    return JwkPublicParametersOneOf1FromJSONTyped(json, false);
}

export function JwkPublicParametersOneOf1FromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): JwkPublicParametersOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        crv: json["crv"],
        kty: json["kty"],
        x: json["x"],
        y: json["y"],
    };
}

export function JwkPublicParametersOneOf1ToJSON(
    json: any,
): JwkPublicParametersOneOf1 {
    return JwkPublicParametersOneOf1ToJSONTyped(json, false);
}

export function JwkPublicParametersOneOf1ToJSONTyped(
    value?: JwkPublicParametersOneOf1 | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        crv: value["crv"],
        kty: value["kty"],
        x: value["x"],
        y: value["y"],
    };
}
