/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface JwkPublicParametersOneOf2
 */
export interface JwkPublicParametersOneOf2 {
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf2
     */
    crv: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf2
     */
    kty: JwkPublicParametersOneOf2KtyEnum;
    /**
     *
     * @type {string}
     * @memberof JwkPublicParametersOneOf2
     */
    x: string;
}

/**
 * @export
 */
export const JwkPublicParametersOneOf2KtyEnum = {
    Opk: "Opk",
} as const;
export type JwkPublicParametersOneOf2KtyEnum =
    (typeof JwkPublicParametersOneOf2KtyEnum)[keyof typeof JwkPublicParametersOneOf2KtyEnum];

/**
 * Check if a given object implements the JwkPublicParametersOneOf2 interface.
 */
export function instanceOfJwkPublicParametersOneOf2(
    value: object,
): value is JwkPublicParametersOneOf2 {
    if (!("crv" in value) || value["crv"] === undefined) return false;
    if (!("kty" in value) || value["kty"] === undefined) return false;
    if (!("x" in value) || value["x"] === undefined) return false;
    return true;
}

export function JwkPublicParametersOneOf2FromJSON(
    json: any,
): JwkPublicParametersOneOf2 {
    return JwkPublicParametersOneOf2FromJSONTyped(json, false);
}

export function JwkPublicParametersOneOf2FromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): JwkPublicParametersOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        crv: json["crv"],
        kty: json["kty"],
        x: json["x"],
    };
}

export function JwkPublicParametersOneOf2ToJSON(
    json: any,
): JwkPublicParametersOneOf2 {
    return JwkPublicParametersOneOf2ToJSONTyped(json, false);
}

export function JwkPublicParametersOneOf2ToJSONTyped(
    value?: JwkPublicParametersOneOf2 | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        crv: value["crv"],
        kty: value["kty"],
        x: value["x"],
    };
}
