/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { JwsAlgorithm } from "./JwsAlgorithm.js";
import {
    JwsAlgorithmFromJSON,
    JwsAlgorithmFromJSONTyped,
    JwsAlgorithmToJSON,
    JwsAlgorithmToJSONTyped,
} from "./JwsAlgorithm.js";
import type { KeyUse } from "./KeyUse.js";
import {
    KeyUseFromJSON,
    KeyUseFromJSONTyped,
    KeyUseToJSON,
    KeyUseToJSONTyped,
} from "./KeyUse.js";

/**
 *
 * @export
 * @interface JwkPublic
 */
export interface JwkPublic {
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    e: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    kty: JwkPublicKtyEnum;
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    n: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    crv: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    x: string;
    /**
     *
     * @type {string}
     * @memberof JwkPublic
     */
    y: string;
    /**
     * Algorithm intended for use
     * @type {JwsAlgorithm}
     * @memberof JwkPublic
     */
    alg: JwsAlgorithm;
    /**
     * Key ID
     * @type {number}
     * @memberof JwkPublic
     */
    kid: number;
    /**
     * Key use (sig, enc)
     * @type {KeyUse}
     * @memberof JwkPublic
     */
    use: KeyUse;
}

/**
 * @export
 */
export const JwkPublicKtyEnum = {
    Opk: "Opk",
} as const;
export type JwkPublicKtyEnum =
    (typeof JwkPublicKtyEnum)[keyof typeof JwkPublicKtyEnum];

/**
 * Check if a given object implements the JwkPublic interface.
 */
export function instanceOfJwkPublic(value: object): value is JwkPublic {
    if (!("e" in value) || value["e"] === undefined) return false;
    if (!("kty" in value) || value["kty"] === undefined) return false;
    if (!("n" in value) || value["n"] === undefined) return false;
    if (!("crv" in value) || value["crv"] === undefined) return false;
    if (!("x" in value) || value["x"] === undefined) return false;
    if (!("y" in value) || value["y"] === undefined) return false;
    if (!("alg" in value) || value["alg"] === undefined) return false;
    if (!("kid" in value) || value["kid"] === undefined) return false;
    if (!("use" in value) || value["use"] === undefined) return false;
    return true;
}

export function JwkPublicFromJSON(json: any): JwkPublic {
    return JwkPublicFromJSONTyped(json, false);
}

export function JwkPublicFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): JwkPublic {
    if (json == null) {
        return json;
    }
    return {
        e: json["e"],
        kty: json["kty"],
        n: json["n"],
        crv: json["crv"],
        x: json["x"],
        y: json["y"],
        alg: JwsAlgorithmFromJSON(json["alg"]),
        kid: json["kid"],
        use: KeyUseFromJSON(json["use"]),
    };
}

export function JwkPublicToJSON(json: any): JwkPublic {
    return JwkPublicToJSONTyped(json, false);
}

export function JwkPublicToJSONTyped(
    value?: JwkPublic | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        e: value["e"],
        kty: value["kty"],
        n: value["n"],
        crv: value["crv"],
        x: value["x"],
        y: value["y"],
        alg: JwsAlgorithmToJSON(value["alg"]),
        kid: value["kid"],
        use: KeyUseToJSON(value["use"]),
    };
}
