/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const KeyUse = {
    Sig: "sig",
    Enc: "enc",
} as const;
export type KeyUse = (typeof KeyUse)[keyof typeof KeyUse];

export function instanceOfKeyUse(value: any): boolean {
    for (const key in KeyUse) {
        if (Object.hasOwn(KeyUse, key)) {
            if (KeyUse[key as keyof typeof KeyUse] === value) {
                return true;
            }
        }
    }
    return false;
}

export function KeyUseFromJSON(json: any): KeyUse {
    return KeyUseFromJSONTyped(json, false);
}

export function KeyUseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KeyUse {
    return json as KeyUse;
}

export function KeyUseToJSON(value?: KeyUse | null): any {
    return value as any;
}

export function KeyUseToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): KeyUse {
    return value as KeyUse;
}
