/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EntityType } from './EntityType.js';
import {
    EntityTypeFromJSON,
    EntityTypeFromJSONTyped,
    EntityTypeToJSON,
    EntityTypeToJSONTyped,
} from './EntityType.js';

/**
 * 
 * @export
 * @interface ManagementKey
 */
export interface ManagementKey {
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof ManagementKey
     */
    derivationPath: string;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    entityId: number;
    /**
     * 
     * @type {EntityType}
     * @memberof ManagementKey
     */
    entityType: EntityType;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    expiresAt?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ManagementKey
     */
    hardened: boolean;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ManagementKey
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    parentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    revokedAt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ManagementKey
     */
    updatedAt: number;
}



/**
 * Check if a given object implements the ManagementKey interface.
 */
export function instanceOfManagementKey(value: object): value is ManagementKey {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('derivationPath' in value) || value['derivationPath'] === undefined) return false;
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    if (!('hardened' in value) || value['hardened'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ManagementKeyFromJSON(json: any): ManagementKey {
    return ManagementKeyFromJSONTyped(json, false);
}

export function ManagementKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementKey {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'derivationPath': json['derivation_path'],
        'entityId': json['entity_id'],
        'entityType': EntityTypeFromJSON(json['entity_type']),
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'hardened': json['hardened'],
        'id': json['id'],
        'name': json['name'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'revokedAt': json['revoked_at'] == null ? undefined : json['revoked_at'],
        'updatedAt': json['updated_at'],
    };
}

export function ManagementKeyToJSON(json: any): ManagementKey {
    return ManagementKeyToJSONTyped(json, false);
}

export function ManagementKeyToJSONTyped(value?: ManagementKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'derivation_path': value['derivationPath'],
        'entity_id': value['entityId'],
        'entity_type': EntityTypeToJSON(value['entityType']),
        'expires_at': value['expiresAt'],
        'hardened': value['hardened'],
        'id': value['id'],
        'name': value['name'],
        'parent_id': value['parentId'],
        'revoked_at': value['revokedAt'],
        'updated_at': value['updatedAt'],
    };
}

