/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface ResetUserPasswordRequest
 */
export interface ResetUserPasswordRequest {
    /**
     *
     * @type {string}
     * @memberof ResetUserPasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ResetUserPasswordRequest interface.
 */
export function instanceOfResetUserPasswordRequest(
    value: object,
): value is ResetUserPasswordRequest {
    if (!("password" in value) || value["password"] === undefined) return false;
    return true;
}

export function ResetUserPasswordRequestFromJSON(
    json: any,
): ResetUserPasswordRequest {
    return ResetUserPasswordRequestFromJSONTyped(json, false);
}

export function ResetUserPasswordRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ResetUserPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        password: json["password"],
    };
}

export function ResetUserPasswordRequestToJSON(
    json: any,
): ResetUserPasswordRequest {
    return ResetUserPasswordRequestToJSONTyped(json, false);
}

export function ResetUserPasswordRequestToJSONTyped(
    value?: ResetUserPasswordRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        password: value["password"],
    };
}
