/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface RoleResponse
 */
export interface RoleResponse {
    /**
     *
     * @type {number}
     * @memberof RoleResponse
     */
    createdAt: number;
    /**
     *
     * @type {string}
     * @memberof RoleResponse
     */
    description?: string | null;
    /**
     *
     * @type {number}
     * @memberof RoleResponse
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof RoleResponse
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof RoleResponse
     */
    updatedAt: number;
}

/**
 * Check if a given object implements the RoleResponse interface.
 */
export function instanceOfRoleResponse(value: object): value is RoleResponse {
    if (!("createdAt" in value) || value["createdAt"] === undefined)
        return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    return true;
}

export function RoleResponseFromJSON(json: any): RoleResponse {
    return RoleResponseFromJSONTyped(json, false);
}

export function RoleResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): RoleResponse {
    if (json == null) {
        return json;
    }
    return {
        createdAt: json["created_at"],
        description:
            json["description"] == null ? undefined : json["description"],
        id: json["id"],
        name: json["name"],
        updatedAt: json["updated_at"],
    };
}

export function RoleResponseToJSON(json: any): RoleResponse {
    return RoleResponseToJSONTyped(json, false);
}

export function RoleResponseToJSONTyped(
    value?: RoleResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        created_at: value["createdAt"],
        description: value["description"],
        id: value["id"],
        name: value["name"],
        updated_at: value["updatedAt"],
    };
}
