/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Client token endpoint authentication methods (RFC 7591 / OIDC).
 * @export
 */
export const TokenEndpointAuthMethod = {
    ClientSecretBasic: "client_secret_basic",
    ClientSecretPost: "client_secret_post",
    PrivateKeyJwt: "private_key_jwt",
    ClientSecretJwt: "client_secret_jwt",
    None: "none",
} as const;
export type TokenEndpointAuthMethod =
    (typeof TokenEndpointAuthMethod)[keyof typeof TokenEndpointAuthMethod];

export function instanceOfTokenEndpointAuthMethod(value: any): boolean {
    for (const key in TokenEndpointAuthMethod) {
        if (
            Object.prototype.hasOwnProperty.call(TokenEndpointAuthMethod, key)
        ) {
            if (
                TokenEndpointAuthMethod[
                    key as keyof typeof TokenEndpointAuthMethod
                ] === value
            ) {
                return true;
            }
        }
    }
    return false;
}

export function TokenEndpointAuthMethodFromJSON(
    json: any,
): TokenEndpointAuthMethod {
    return TokenEndpointAuthMethodFromJSONTyped(json, false);
}

export function TokenEndpointAuthMethodFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TokenEndpointAuthMethod {
    return json as TokenEndpointAuthMethod;
}

export function TokenEndpointAuthMethodToJSON(
    value?: TokenEndpointAuthMethod | null,
): any {
    return value as any;
}

export function TokenEndpointAuthMethodToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): TokenEndpointAuthMethod {
    return value as TokenEndpointAuthMethod;
}
