/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    birthdate?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    emailVerified?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    familyName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    givenName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    locale?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    middleName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    nickname?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    phoneNumber?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    phoneNumberVerified?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    picture?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    profile?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    sex?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    website?: string | null;
    /**
     *
     * @type {string}
     * @memberof UpdateUserRequest
     */
    zoneinfo?: string | null;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(
    value: object,
): value is UpdateUserRequest {
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        birthdate: json["birthdate"] == null ? undefined : json["birthdate"],
        email: json["email"] == null ? undefined : json["email"],
        emailVerified:
            json["email_verified"] == null ? undefined : json["email_verified"],
        familyName:
            json["family_name"] == null ? undefined : json["family_name"],
        givenName: json["given_name"] == null ? undefined : json["given_name"],
        locale: json["locale"] == null ? undefined : json["locale"],
        middleName:
            json["middle_name"] == null ? undefined : json["middle_name"],
        name: json["name"] == null ? undefined : json["name"],
        nickname: json["nickname"] == null ? undefined : json["nickname"],
        phoneNumber:
            json["phone_number"] == null ? undefined : json["phone_number"],
        phoneNumberVerified:
            json["phone_number_verified"] == null
                ? undefined
                : json["phone_number_verified"],
        picture: json["picture"] == null ? undefined : json["picture"],
        profile: json["profile"] == null ? undefined : json["profile"],
        sex: json["sex"] == null ? undefined : json["sex"],
        website: json["website"] == null ? undefined : json["website"],
        zoneinfo: json["zoneinfo"] == null ? undefined : json["zoneinfo"],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(
    value?: UpdateUserRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        birthdate: value["birthdate"],
        email: value["email"],
        email_verified: value["emailVerified"],
        family_name: value["familyName"],
        given_name: value["givenName"],
        locale: value["locale"],
        middle_name: value["middleName"],
        name: value["name"],
        nickname: value["nickname"],
        phone_number: value["phoneNumber"],
        phone_number_verified: value["phoneNumberVerified"],
        picture: value["picture"],
        profile: value["profile"],
        sex: value["sex"],
        website: value["website"],
        zoneinfo: value["zoneinfo"],
    };
}
