/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserConsentResponse
 */
export interface UserConsentResponse {
    /**
     * 
     * @type {string}
     * @memberof UserConsentResponse
     */
    clientId: string;
    /**
     * 
     * @type {number}
     * @memberof UserConsentResponse
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof UserConsentResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserConsentResponse
     */
    redirectUri: string;
    /**
     * 
     * @type {string}
     * @memberof UserConsentResponse
     */
    scope: string;
    /**
     * 
     * @type {number}
     * @memberof UserConsentResponse
     */
    updatedAt: number;
    /**
     * 
     * @type {number}
     * @memberof UserConsentResponse
     */
    userId: number;
}

/**
 * Check if a given object implements the UserConsentResponse interface.
 */
export function instanceOfUserConsentResponse(value: object): value is UserConsentResponse {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserConsentResponseFromJSON(json: any): UserConsentResponse {
    return UserConsentResponseFromJSONTyped(json, false);
}

export function UserConsentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConsentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'createdAt': json['created_at'],
        'id': json['id'],
        'redirectUri': json['redirect_uri'],
        'scope': json['scope'],
        'updatedAt': json['updated_at'],
        'userId': json['user_id'],
    };
}

export function UserConsentResponseToJSON(json: any): UserConsentResponse {
    return UserConsentResponseToJSONTyped(json, false);
}

export function UserConsentResponseToJSONTyped(value?: UserConsentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'redirect_uri': value['redirectUri'],
        'scope': value['scope'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

