/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    birthdate?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    email?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof UserInfo
     */
    emailVerified?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    familyName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    gender?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    givenName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    locale?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    middleName?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    nickname?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    phoneNumber?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof UserInfo
     */
    phoneNumberVerified?: boolean | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    picture?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    preferredUsername?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    profile?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    sub: string;
    /**
     *
     * @type {Date}
     * @memberof UserInfo
     */
    updatedAt: Date;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    website?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserInfo
     */
    zoneinfo?: string | null;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
    if (!("sub" in value) || value["sub"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        birthdate: json["birthdate"] == null ? undefined : json["birthdate"],
        email: json["email"] == null ? undefined : json["email"],
        emailVerified:
            json["email_verified"] == null ? undefined : json["email_verified"],
        familyName:
            json["family_name"] == null ? undefined : json["family_name"],
        gender: json["gender"] == null ? undefined : json["gender"],
        givenName: json["given_name"] == null ? undefined : json["given_name"],
        locale: json["locale"] == null ? undefined : json["locale"],
        middleName:
            json["middle_name"] == null ? undefined : json["middle_name"],
        name: json["name"] == null ? undefined : json["name"],
        nickname: json["nickname"] == null ? undefined : json["nickname"],
        phoneNumber:
            json["phone_number"] == null ? undefined : json["phone_number"],
        phoneNumberVerified:
            json["phone_number_verified"] == null
                ? undefined
                : json["phone_number_verified"],
        picture: json["picture"] == null ? undefined : json["picture"],
        preferredUsername:
            json["preferred_username"] == null
                ? undefined
                : json["preferred_username"],
        profile: json["profile"] == null ? undefined : json["profile"],
        sub: json["sub"],
        updatedAt: new Date(json["updated_at"]),
        website: json["website"] == null ? undefined : json["website"],
        zoneinfo: json["zoneinfo"] == null ? undefined : json["zoneinfo"],
    };
}

export function UserInfoToJSON(json: any): UserInfo {
    return UserInfoToJSONTyped(json, false);
}

export function UserInfoToJSONTyped(
    value?: UserInfo | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        birthdate: value["birthdate"],
        email: value["email"],
        email_verified: value["emailVerified"],
        family_name: value["familyName"],
        gender: value["gender"],
        given_name: value["givenName"],
        locale: value["locale"],
        middle_name: value["middleName"],
        name: value["name"],
        nickname: value["nickname"],
        phone_number: value["phoneNumber"],
        phone_number_verified: value["phoneNumberVerified"],
        picture: value["picture"],
        preferred_username: value["preferredUsername"],
        profile: value["profile"],
        sub: value["sub"],
        updated_at: value["updatedAt"].toISOString(),
        website: value["website"],
        zoneinfo: value["zoneinfo"],
    };
}
