/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UserRoleResponse
 */
export interface UserRoleResponse {
    /**
     *
     * @type {string}
     * @memberof UserRoleResponse
     */
    applicationId: string;
    /**
     *
     * @type {number}
     * @memberof UserRoleResponse
     */
    createdAt: number;
    /**
     *
     * @type {number}
     * @memberof UserRoleResponse
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof UserRoleResponse
     */
    roleId: number;
    /**
     *
     * @type {string}
     * @memberof UserRoleResponse
     */
    roleName: string;
    /**
     *
     * @type {number}
     * @memberof UserRoleResponse
     */
    updatedAt: number;
    /**
     *
     * @type {number}
     * @memberof UserRoleResponse
     */
    userId: number;
}

/**
 * Check if a given object implements the UserRoleResponse interface.
 */
export function instanceOfUserRoleResponse(
    value: object,
): value is UserRoleResponse {
    if (!("applicationId" in value) || value["applicationId"] === undefined)
        return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined)
        return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("roleId" in value) || value["roleId"] === undefined) return false;
    if (!("roleName" in value) || value["roleName"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    if (!("userId" in value) || value["userId"] === undefined) return false;
    return true;
}

export function UserRoleResponseFromJSON(json: any): UserRoleResponse {
    return UserRoleResponseFromJSONTyped(json, false);
}

export function UserRoleResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        applicationId: json["application_id"],
        createdAt: json["created_at"],
        id: json["id"],
        roleId: json["role_id"],
        roleName: json["role_name"],
        updatedAt: json["updated_at"],
        userId: json["user_id"],
    };
}

export function UserRoleResponseToJSON(json: any): UserRoleResponse {
    return UserRoleResponseToJSONTyped(json, false);
}

export function UserRoleResponseToJSONTyped(
    value?: UserRoleResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        application_id: value["applicationId"],
        created_at: value["createdAt"],
        id: value["id"],
        role_id: value["roleId"],
        role_name: value["roleName"],
        updated_at: value["updatedAt"],
        user_id: value["userId"],
    };
}
