/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface UserApplicationRoleResponse
 */
export interface UserApplicationRoleResponse {
    /**
     *
     * @type {number}
     * @memberof UserApplicationRoleResponse
     */
    applicationId: number;
    /**
     *
     * @type {number}
     * @memberof UserApplicationRoleResponse
     */
    createdAt: number;
    /**
     *
     * @type {string}
     * @memberof UserApplicationRoleResponse
     */
    roleDescription?: string | null;
    /**
     *
     * @type {number}
     * @memberof UserApplicationRoleResponse
     */
    roleId: number;
    /**
     *
     * @type {string}
     * @memberof UserApplicationRoleResponse
     */
    roleName: string;
    /**
     *
     * @type {number}
     * @memberof UserApplicationRoleResponse
     */
    updatedAt: number;
}

/**
 * Check if a given object implements the UserApplicationRoleResponse interface.
 */
export function instanceOfUserApplicationRoleResponse(
    value: object,
): value is UserApplicationRoleResponse {
    if (!("applicationId" in value) || value["applicationId"] === undefined)
        return false;
    if (!("createdAt" in value) || value["createdAt"] === undefined)
        return false;
    if (!("roleId" in value) || value["roleId"] === undefined) return false;
    if (!("roleName" in value) || value["roleName"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined)
        return false;
    return true;
}

export function UserApplicationRoleResponseFromJSON(
    json: any,
): UserApplicationRoleResponse {
    return UserApplicationRoleResponseFromJSONTyped(json, false);
}

export function UserApplicationRoleResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UserApplicationRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        applicationId: json["application_id"],
        createdAt: json["created_at"],
        roleDescription:
            json["role_description"] == null
                ? undefined
                : json["role_description"],
        roleId: json["role_id"],
        roleName: json["role_name"],
        updatedAt: json["updated_at"],
    };
}

export function UserApplicationRoleResponseToJSON(
    json: any,
): UserApplicationRoleResponse {
    return UserApplicationRoleResponseToJSONTyped(json, false);
}

export function UserApplicationRoleResponseToJSONTyped(
    value?: UserApplicationRoleResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        application_id: value["applicationId"],
        created_at: value["createdAt"],
        role_description: value["roleDescription"],
        role_id: value["roleId"],
        role_name: value["roleName"],
        updated_at: value["updatedAt"],
    };
}
