/* tslint:disable */
/* eslint-disable */
/**
 * LIDP Management API
 * Management API server for LIDP
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * 
     * @type {Date}
     * @memberof VersionResponse
     */
    build: Date;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    version: string;
}

/**
 * Check if a given object implements the VersionResponse interface.
 */
export function instanceOfVersionResponse(value: object): value is VersionResponse {
    if (!('build' in value) || value['build'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function VersionResponseFromJSON(json: any): VersionResponse {
    return VersionResponseFromJSONTyped(json, false);
}

export function VersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'build': (new Date(json['build'])),
        'version': json['version'],
    };
}

export function VersionResponseToJSON(json: any): VersionResponse {
    return VersionResponseToJSONTyped(json, false);
}

export function VersionResponseToJSONTyped(value?: VersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build': ((value['build']).toISOString()),
        'version': value['version'],
    };
}

