/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ApproveForUserRequest
 */
export interface ApproveForUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ApproveForUserRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof ApproveForUserRequest
     */
    redirectUri: string;
    /**
     * 
     * @type {string}
     * @memberof ApproveForUserRequest
     */
    scope: string;
}

/**
 * Check if a given object implements the ApproveForUserRequest interface.
 */
export function instanceOfApproveForUserRequest(value: object): value is ApproveForUserRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ApproveForUserRequestFromJSON(json: any): ApproveForUserRequest {
    return ApproveForUserRequestFromJSONTyped(json, false);
}

export function ApproveForUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveForUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'redirectUri': json['redirect_uri'],
        'scope': json['scope'],
    };
}

export function ApproveForUserRequestToJSON(json: any): ApproveForUserRequest {
    return ApproveForUserRequestToJSONTyped(json, false);
}

export function ApproveForUserRequestToJSONTyped(value?: ApproveForUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'redirect_uri': value['redirectUri'],
        'scope': value['scope'],
    };
}

