/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ErrorCode } from './ErrorCode.js';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
    ErrorCodeToJSONTyped,
} from './ErrorCode.js';

/**
 * 
 * @export
 * @interface AuthorizationCodeResponseOneOf1
 */
export interface AuthorizationCodeResponseOneOf1 {
    /**
     * 
     * @type {ErrorCode}
     * @memberof AuthorizationCodeResponseOneOf1
     */
    error: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf1
     */
    errorDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf1
     */
    errorUri?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf1
     */
    state: string;
}



/**
 * Check if a given object implements the AuthorizationCodeResponseOneOf1 interface.
 */
export function instanceOfAuthorizationCodeResponseOneOf1(value: object): value is AuthorizationCodeResponseOneOf1 {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function AuthorizationCodeResponseOneOf1FromJSON(json: any): AuthorizationCodeResponseOneOf1 {
    return AuthorizationCodeResponseOneOf1FromJSONTyped(json, false);
}

export function AuthorizationCodeResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationCodeResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': ErrorCodeFromJSON(json['error']),
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
        'errorUri': json['error_uri'] == null ? undefined : json['error_uri'],
        'state': json['state'],
    };
}

export function AuthorizationCodeResponseOneOf1ToJSON(json: any): AuthorizationCodeResponseOneOf1 {
    return AuthorizationCodeResponseOneOf1ToJSONTyped(json, false);
}

export function AuthorizationCodeResponseOneOf1ToJSONTyped(value?: AuthorizationCodeResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': ErrorCodeToJSON(value['error']),
        'error_description': value['errorDescription'],
        'error_uri': value['errorUri'],
        'state': value['state'],
    };
}

