/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuthorizationCodeResponseOneOf
 */
export interface AuthorizationCodeResponseOneOf {
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf
     */
    iss?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationCodeResponseOneOf
     */
    state?: string | null;
}

/**
 * Check if a given object implements the AuthorizationCodeResponseOneOf interface.
 */
export function instanceOfAuthorizationCodeResponseOneOf(value: object): value is AuthorizationCodeResponseOneOf {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthorizationCodeResponseOneOfFromJSON(json: any): AuthorizationCodeResponseOneOf {
    return AuthorizationCodeResponseOneOfFromJSONTyped(json, false);
}

export function AuthorizationCodeResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationCodeResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'iss': json['iss'] == null ? undefined : json['iss'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function AuthorizationCodeResponseOneOfToJSON(json: any): AuthorizationCodeResponseOneOf {
    return AuthorizationCodeResponseOneOfToJSONTyped(json, false);
}

export function AuthorizationCodeResponseOneOfToJSONTyped(value?: AuthorizationCodeResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'iss': value['iss'],
        'state': value['state'],
    };
}

