/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { CodeChallengeMethod } from "./CodeChallengeMethod.js";
import {
    CodeChallengeMethodFromJSON,
    CodeChallengeMethodFromJSONTyped,
    CodeChallengeMethodToJSON,
    CodeChallengeMethodToJSONTyped,
} from "./CodeChallengeMethod.js";
import type { ResponseMode } from "./ResponseMode.js";
import {
    ResponseModeFromJSON,
    ResponseModeFromJSONTyped,
    ResponseModeToJSON,
    ResponseModeToJSONTyped,
} from "./ResponseMode.js";
import type { ResponseType } from "./ResponseType.js";
import {
    ResponseTypeFromJSON,
    ResponseTypeFromJSONTyped,
    ResponseTypeToJSON,
    ResponseTypeToJSONTyped,
} from "./ResponseType.js";

/**
 *
 * @export
 * @interface AuthorizationRequest
 */
export interface AuthorizationRequest {
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    clientId: string;
    /**
     * PKCE parameters (RFC 7636) for public clients and enhanced security
     * @type {string}
     * @memberof AuthorizationRequest
     */
    codeChallenge?: string | null;
    /**
     * The method used to derive the code challenge (e.g., "S256" or "plain").
     * only required if `code_challenge` is present. "S256" is strongly recommended in OAuth 2.1 for better security.
     * @type {CodeChallengeMethod}
     * @memberof AuthorizationRequest
     */
    codeChallengeMethod?: CodeChallengeMethod | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    idTokenHint?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    loginHint?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    nonce?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    prompt?: string | null;
    /**
     * redirect URI is optional if the client has only one registered redirect URI
     * @type {string}
     * @memberof AuthorizationRequest
     */
    redirectUri?: string | null;
    /**
     * Audience parameter (RFC 8707) to specify the intended recipients of the token.
     * @type {string}
     * @memberof AuthorizationRequest
     */
    resource?: string | null;
    /**
     *
     * @type {ResponseMode}
     * @memberof AuthorizationRequest
     */
    responseMode?: ResponseMode | null;
    /**
     *
     * @type {ResponseType}
     * @memberof AuthorizationRequest
     */
    responseType: ResponseType;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    scope?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    state?: string | null;
    /**
     *
     * @type {string}
     * @memberof AuthorizationRequest
     */
    uiLocales?: string | null;
}

/**
 * Check if a given object implements the AuthorizationRequest interface.
 */
export function instanceOfAuthorizationRequest(
    value: object,
): value is AuthorizationRequest {
    if (!("clientId" in value) || value["clientId"] === undefined) return false;
    if (!("responseType" in value) || value["responseType"] === undefined)
        return false;
    return true;
}

export function AuthorizationRequestFromJSON(json: any): AuthorizationRequest {
    return AuthorizationRequestFromJSONTyped(json, false);
}

export function AuthorizationRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        clientId: json["client_id"],
        codeChallenge:
            json["code_challenge"] == null ? undefined : json["code_challenge"],
        codeChallengeMethod:
            json["code_challenge_method"] == null
                ? undefined
                : CodeChallengeMethodFromJSON(json["code_challenge_method"]),
        idTokenHint:
            json["id_token_hint"] == null ? undefined : json["id_token_hint"],
        loginHint: json["login_hint"] == null ? undefined : json["login_hint"],
        nonce: json["nonce"] == null ? undefined : json["nonce"],
        prompt: json["prompt"] == null ? undefined : json["prompt"],
        redirectUri:
            json["redirect_uri"] == null ? undefined : json["redirect_uri"],
        resource: json["resource"] == null ? undefined : json["resource"],
        responseMode:
            json["response_mode"] == null
                ? undefined
                : ResponseModeFromJSON(json["response_mode"]),
        responseType: ResponseTypeFromJSON(json["response_type"]),
        scope: json["scope"] == null ? undefined : json["scope"],
        state: json["state"] == null ? undefined : json["state"],
        uiLocales: json["ui_locales"] == null ? undefined : json["ui_locales"],
    };
}

export function AuthorizationRequestToJSON(json: any): AuthorizationRequest {
    return AuthorizationRequestToJSONTyped(json, false);
}

export function AuthorizationRequestToJSONTyped(
    value?: AuthorizationRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        client_id: value["clientId"],
        code_challenge: value["codeChallenge"],
        code_challenge_method: CodeChallengeMethodToJSON(
            value["codeChallengeMethod"],
        ),
        id_token_hint: value["idTokenHint"],
        login_hint: value["loginHint"],
        nonce: value["nonce"],
        prompt: value["prompt"],
        redirect_uri: value["redirectUri"],
        resource: value["resource"],
        response_mode: ResponseModeToJSON(value["responseMode"]),
        response_type: ResponseTypeToJSON(value["responseType"]),
        scope: value["scope"],
        state: value["state"],
        ui_locales: value["uiLocales"],
    };
}
