/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthorizationCodeResponseOneOf } from "./AuthorizationCodeResponseOneOf.js";
import {
    instanceOfAuthorizationCodeResponseOneOf,
    AuthorizationCodeResponseOneOfFromJSON,
    AuthorizationCodeResponseOneOfFromJSONTyped,
    AuthorizationCodeResponseOneOfToJSON,
} from "./AuthorizationCodeResponseOneOf.js";
import type { AuthorizationCodeResponseOneOf1 } from "./AuthorizationCodeResponseOneOf1.js";
import {
    instanceOfAuthorizationCodeResponseOneOf1,
    AuthorizationCodeResponseOneOf1FromJSON,
    AuthorizationCodeResponseOneOf1FromJSONTyped,
    AuthorizationCodeResponseOneOf1ToJSON,
} from "./AuthorizationCodeResponseOneOf1.js";

/**
 * @type AuthorizationCodeResponse
 *
 * @export
 */
export type AuthorizationCodeResponse =
    | AuthorizationCodeResponseOneOf
    | AuthorizationCodeResponseOneOf1;

export function AuthorizationCodeResponseFromJSON(
    json: any,
): AuthorizationCodeResponse {
    return AuthorizationCodeResponseFromJSONTyped(json, false);
}

export function AuthorizationCodeResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): AuthorizationCodeResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== "object") {
        return json;
    }
    if (instanceOfAuthorizationCodeResponseOneOf(json)) {
        return AuthorizationCodeResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfAuthorizationCodeResponseOneOf1(json)) {
        return AuthorizationCodeResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function AuthorizationCodeResponseToJSON(json: any): any {
    return AuthorizationCodeResponseToJSONTyped(json, false);
}

export function AuthorizationCodeResponseToJSONTyped(
    value?: AuthorizationCodeResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== "object") {
        return value;
    }
    if (instanceOfAuthorizationCodeResponseOneOf(value)) {
        return AuthorizationCodeResponseOneOfToJSON(
            value as AuthorizationCodeResponseOneOf,
        );
    }
    if (instanceOfAuthorizationCodeResponseOneOf1(value)) {
        return AuthorizationCodeResponseOneOf1ToJSON(
            value as AuthorizationCodeResponseOneOf1,
        );
    }

    return {};
}
