/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ClientProfile = {
    WebApplication: "web_application",
    UserAgentBasedApplication: "user_agent_based_application",
    NativeApplication: "native_application",
} as const;
export type ClientProfile = (typeof ClientProfile)[keyof typeof ClientProfile];

export function instanceOfClientProfile(value: any): boolean {
    for (const key in ClientProfile) {
        if (Object.hasOwn(ClientProfile, key)) {
            if (ClientProfile[key as keyof typeof ClientProfile] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ClientProfileFromJSON(json: any): ClientProfile {
    return ClientProfileFromJSONTyped(json, false);
}

export function ClientProfileFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): ClientProfile {
    return json as ClientProfile;
}

export function ClientProfileToJSON(value?: ClientProfile | null): any {
    return value as any;
}

export function ClientProfileToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): ClientProfile {
    return value as ClientProfile;
}
