/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PKCE code challenge methods (RFC 7636).
 * the `plain` method is not included as it is not recommended in OAuth 2.1 due to security weaknesses. Only `S256` is supported for better security.
 * @export
 */
export const CodeChallengeMethod = {
    S256: 'S256'
} as const;
export type CodeChallengeMethod = typeof CodeChallengeMethod[keyof typeof CodeChallengeMethod];


export function instanceOfCodeChallengeMethod(value: any): boolean {
    for (const key in CodeChallengeMethod) {
        if (Object.prototype.hasOwnProperty.call(CodeChallengeMethod, key)) {
            if (CodeChallengeMethod[key as keyof typeof CodeChallengeMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CodeChallengeMethodFromJSON(json: any): CodeChallengeMethod {
    return CodeChallengeMethodFromJSONTyped(json, false);
}

export function CodeChallengeMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeChallengeMethod {
    return json as CodeChallengeMethod;
}

export function CodeChallengeMethodToJSON(value?: CodeChallengeMethod | null): any {
    return value as any;
}

export function CodeChallengeMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): CodeChallengeMethod {
    return value as CodeChallengeMethod;
}

