/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GrantType = {
    Password: 'password',
    AuthorizationCode: 'authorization_code',
    ClientCredentials: 'client_credentials',
    RefreshToken: 'refresh_token'
} as const;
export type GrantType = typeof GrantType[keyof typeof GrantType];


export function instanceOfGrantType(value: any): boolean {
    for (const key in GrantType) {
        if (Object.prototype.hasOwnProperty.call(GrantType, key)) {
            if (GrantType[key as keyof typeof GrantType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GrantTypeFromJSON(json: any): GrantType {
    return GrantTypeFromJSONTyped(json, false);
}

export function GrantTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantType {
    return json as GrantType;
}

export function GrantTypeToJSON(value?: GrantType | null): any {
    return value as any;
}

export function GrantTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): GrantType {
    return value as GrantType;
}

