/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HealthStatusOneOf } from "./HealthStatusOneOf.js";
import {
    instanceOfHealthStatusOneOf,
    HealthStatusOneOfFromJSON,
    HealthStatusOneOfFromJSONTyped,
    HealthStatusOneOfToJSON,
} from "./HealthStatusOneOf.js";

/**
 * @type HealthStatus
 *
 * @export
 */
export type HealthStatus = HealthStatusOneOf | string;

export function HealthStatusFromJSON(json: any): HealthStatus {
    return HealthStatusFromJSONTyped(json, false);
}

export function HealthStatusFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): HealthStatus {
    if (json == null) {
        return json;
    }
    if (typeof json !== "object") {
        return json;
    }
    if (instanceOfHealthStatusOneOf(json)) {
        return HealthStatusOneOfFromJSONTyped(json, true);
    }

    return {} as any;
}

export function HealthStatusToJSON(json: any): any {
    return HealthStatusToJSONTyped(json, false);
}

export function HealthStatusToJSONTyped(
    value?: HealthStatus | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== "object") {
        return value;
    }
    if (instanceOfHealthStatusOneOf(value)) {
        return HealthStatusOneOfToJSON(value as HealthStatusOneOf);
    }

    return {};
}
