/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
import type { HealthStatus } from "./HealthStatus.js";
import {
    HealthStatusFromJSON,
    HealthStatusFromJSONTyped,
    HealthStatusToJSON,
    HealthStatusToJSONTyped,
} from "./HealthStatus.js";

/**
 *
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     *
     * @type {HealthStatus}
     * @memberof HealthResponse
     */
    database: HealthStatus;
}

/**
 * Check if a given object implements the HealthResponse interface.
 */
export function instanceOfHealthResponse(
    value: object,
): value is HealthResponse {
    if (!("database" in value) || value["database"] === undefined) return false;
    return true;
}

export function HealthResponseFromJSON(json: any): HealthResponse {
    return HealthResponseFromJSONTyped(json, false);
}

export function HealthResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): HealthResponse {
    if (json == null) {
        return json;
    }
    return {
        database: HealthStatusFromJSON(json["database"]),
    };
}

export function HealthResponseToJSON(json: any): HealthResponse {
    return HealthResponseToJSONTyped(json, false);
}

export function HealthResponseToJSONTyped(
    value?: HealthResponse | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        database: HealthStatusToJSON(value["database"]),
    };
}
