/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface HealthStatusOneOf
 */
export interface HealthStatusOneOf {
    /**
     *
     * @type {string}
     * @memberof HealthStatusOneOf
     */
    unhealthy: string;
}

/**
 * Check if a given object implements the HealthStatusOneOf interface.
 */
export function instanceOfHealthStatusOneOf(
    value: object,
): value is HealthStatusOneOf {
    if (!("unhealthy" in value) || value["unhealthy"] === undefined)
        return false;
    return true;
}

export function HealthStatusOneOfFromJSON(json: any): HealthStatusOneOf {
    return HealthStatusOneOfFromJSONTyped(json, false);
}

export function HealthStatusOneOfFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): HealthStatusOneOf {
    if (json == null) {
        return json;
    }
    return {
        unhealthy: json["unhealthy"],
    };
}

export function HealthStatusOneOfToJSON(json: any): HealthStatusOneOf {
    return HealthStatusOneOfToJSONTyped(json, false);
}

export function HealthStatusOneOfToJSONTyped(
    value?: HealthStatusOneOf | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        unhealthy: value["unhealthy"],
    };
}
