/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IsAllowedForUserResponse
 */
export interface IsAllowedForUserResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IsAllowedForUserResponse
     */
    allowed: boolean;
}

/**
 * Check if a given object implements the IsAllowedForUserResponse interface.
 */
export function instanceOfIsAllowedForUserResponse(value: object): value is IsAllowedForUserResponse {
    if (!('allowed' in value) || value['allowed'] === undefined) return false;
    return true;
}

export function IsAllowedForUserResponseFromJSON(json: any): IsAllowedForUserResponse {
    return IsAllowedForUserResponseFromJSONTyped(json, false);
}

export function IsAllowedForUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsAllowedForUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed': json['allowed'],
    };
}

export function IsAllowedForUserResponseToJSON(json: any): IsAllowedForUserResponse {
    return IsAllowedForUserResponseToJSONTyped(json, false);
}

export function IsAllowedForUserResponseToJSONTyped(value?: IsAllowedForUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed': value['allowed'],
    };
}

