/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.js";
/**
 *
 * @export
 * @interface IsAllowedForUserRequest
 */
export interface IsAllowedForUserRequest {
    /**
     *
     * @type {string}
     * @memberof IsAllowedForUserRequest
     */
    clientId: string;
    /**
     *
     * @type {string}
     * @memberof IsAllowedForUserRequest
     */
    redirectUri: string;
    /**
     *
     * @type {string}
     * @memberof IsAllowedForUserRequest
     */
    scope: string;
}

/**
 * Check if a given object implements the IsAllowedForUserRequest interface.
 */
export function instanceOfIsAllowedForUserRequest(
    value: object,
): value is IsAllowedForUserRequest {
    if (!("clientId" in value) || value["clientId"] === undefined) return false;
    if (!("redirectUri" in value) || value["redirectUri"] === undefined)
        return false;
    if (!("scope" in value) || value["scope"] === undefined) return false;
    return true;
}

export function IsAllowedForUserRequestFromJSON(
    json: any,
): IsAllowedForUserRequest {
    return IsAllowedForUserRequestFromJSONTyped(json, false);
}

export function IsAllowedForUserRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): IsAllowedForUserRequest {
    if (json == null) {
        return json;
    }
    return {
        clientId: json["client_id"],
        redirectUri: json["redirect_uri"],
        scope: json["scope"],
    };
}

export function IsAllowedForUserRequestToJSON(
    json: any,
): IsAllowedForUserRequest {
    return IsAllowedForUserRequestToJSONTyped(json, false);
}

export function IsAllowedForUserRequestToJSONTyped(
    value?: IsAllowedForUserRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        client_id: value["clientId"],
        redirect_uri: value["redirectUri"],
        scope: value["scope"],
    };
}
