/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface JwkPublicParametersOneOf
 */
export interface JwkPublicParametersOneOf {
    /**
     * 
     * @type {string}
     * @memberof JwkPublicParametersOneOf
     */
    e: string;
    /**
     * 
     * @type {string}
     * @memberof JwkPublicParametersOneOf
     */
    kty: JwkPublicParametersOneOfKtyEnum;
    /**
     * 
     * @type {string}
     * @memberof JwkPublicParametersOneOf
     */
    n: string;
}


/**
 * @export
 */
export const JwkPublicParametersOneOfKtyEnum = {
    Rsa: 'Rsa'
} as const;
export type JwkPublicParametersOneOfKtyEnum = typeof JwkPublicParametersOneOfKtyEnum[keyof typeof JwkPublicParametersOneOfKtyEnum];


/**
 * Check if a given object implements the JwkPublicParametersOneOf interface.
 */
export function instanceOfJwkPublicParametersOneOf(value: object): value is JwkPublicParametersOneOf {
    if (!('e' in value) || value['e'] === undefined) return false;
    if (!('kty' in value) || value['kty'] === undefined) return false;
    if (!('n' in value) || value['n'] === undefined) return false;
    return true;
}

export function JwkPublicParametersOneOfFromJSON(json: any): JwkPublicParametersOneOf {
    return JwkPublicParametersOneOfFromJSONTyped(json, false);
}

export function JwkPublicParametersOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwkPublicParametersOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'e': json['e'],
        'kty': json['kty'],
        'n': json['n'],
    };
}

export function JwkPublicParametersOneOfToJSON(json: any): JwkPublicParametersOneOf {
    return JwkPublicParametersOneOfToJSONTyped(json, false);
}

export function JwkPublicParametersOneOfToJSONTyped(value?: JwkPublicParametersOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'e': value['e'],
        'kty': value['kty'],
        'n': value['n'],
    };
}

