/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { JwkPublic } from './JwkPublic.js';
import {
    JwkPublicFromJSON,
    JwkPublicFromJSONTyped,
    JwkPublicToJSON,
    JwkPublicToJSONTyped,
} from './JwkPublic.js';

/**
 * 
 * @export
 * @interface Jwks
 */
export interface Jwks {
    /**
     * 
     * @type {Array<JwkPublic>}
     * @memberof Jwks
     */
    keys: Array<JwkPublic>;
}

/**
 * Check if a given object implements the Jwks interface.
 */
export function instanceOfJwks(value: object): value is Jwks {
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function JwksFromJSON(json: any): Jwks {
    return JwksFromJSONTyped(json, false);
}

export function JwksFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jwks {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': ((json['keys'] as Array<any>).map(JwkPublicFromJSON)),
    };
}

export function JwksToJSON(json: any): Jwks {
    return JwksToJSONTyped(json, false);
}

export function JwksToJSONTyped(value?: Jwks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': ((value['keys'] as Array<any>).map(JwkPublicToJSON)),
    };
}

