/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Valid OAuth 2.0 response types for the authorization endpoint.
 * we do not support the `token` or `id_token` response type (implicit flow) as it is not recommended in OAuth 2.1 and has security weaknesses.
 * @export
 */
export const ResponseType = {
    Code: 'code'
} as const;
export type ResponseType = typeof ResponseType[keyof typeof ResponseType];


export function instanceOfResponseType(value: any): boolean {
    for (const key in ResponseType) {
        if (Object.prototype.hasOwnProperty.call(ResponseType, key)) {
            if (ResponseType[key as keyof typeof ResponseType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseTypeFromJSON(json: any): ResponseType {
    return ResponseTypeFromJSONTyped(json, false);
}

export function ResponseTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseType {
    return json as ResponseType;
}

export function ResponseTypeToJSON(value?: ResponseType | null): any {
    return value as any;
}

export function ResponseTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseType {
    return value as ResponseType;
}

