/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SubjectTokenType = {
    UrnIetfParamsOauthTokenTypeJwt: 'urn:ietf:params:oauth:token-type:jwt',
    UrnIetfParamsOauthTokenTypeAccessToken: 'urn:ietf:params:oauth:token-type:access_token',
    UrnIetfParamsOauthTokenTypeRefreshToken: 'urn:ietf:params:oauth:token-type:refresh_token',
    UrnIetfParamsOauthTokenTypeIdToken: 'urn:ietf:params:oauth:token-type:id_token',
    UrnIetfParamsOauthTokenTypeSaml1: 'urn:ietf:params:oauth:token-type:saml1',
    UrnIetfParamsOauthTokenTypeSaml2: 'urn:ietf:params:oauth:token-type:saml2'
} as const;
export type SubjectTokenType = typeof SubjectTokenType[keyof typeof SubjectTokenType];


export function instanceOfSubjectTokenType(value: any): boolean {
    for (const key in SubjectTokenType) {
        if (Object.prototype.hasOwnProperty.call(SubjectTokenType, key)) {
            if (SubjectTokenType[key as keyof typeof SubjectTokenType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubjectTokenTypeFromJSON(json: any): SubjectTokenType {
    return SubjectTokenTypeFromJSONTyped(json, false);
}

export function SubjectTokenTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectTokenType {
    return json as SubjectTokenType;
}

export function SubjectTokenTypeToJSON(value?: SubjectTokenType | null): any {
    return value as any;
}

export function SubjectTokenTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SubjectTokenType {
    return value as SubjectTokenType;
}

