/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TokenType } from './TokenType.js';
import {
    TokenTypeFromJSON,
    TokenTypeFromJSONTyped,
    TokenTypeToJSON,
    TokenTypeToJSONTyped,
} from './TokenType.js';

/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    accessToken: string;
    /**
     * The lifetime in seconds of the access token.
     * @type {number}
     * @memberof TokenResponse
     */
    expiresIn?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    idToken: string;
    /**
     * The identifier of the authorization server that issued the token.
     * @type {string}
     * @memberof TokenResponse
     */
    iss?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    refreshToken?: string;
    /**
     * The scope of the access token as described by the authorization server.
     * @type {string}
     * @memberof TokenResponse
     */
    scope?: string | null;
    /**
     * The type of the token issued.
     * @type {TokenType}
     * @memberof TokenResponse
     */
    tokenType: TokenType;
}



/**
 * Check if a given object implements the TokenResponse interface.
 */
export function instanceOfTokenResponse(value: object): value is TokenResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('idToken' in value) || value['idToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    return true;
}

export function TokenResponseFromJSON(json: any): TokenResponse {
    return TokenResponseFromJSONTyped(json, false);
}

export function TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'idToken': json['id_token'],
        'iss': json['iss'] == null ? undefined : json['iss'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'tokenType': TokenTypeFromJSON(json['token_type']),
    };
}

export function TokenResponseToJSON(json: any): TokenResponse {
    return TokenResponseToJSONTyped(json, false);
}

export function TokenResponseToJSONTyped(value?: TokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'id_token': value['idToken'],
        'iss': value['iss'],
        'refresh_token': value['refreshToken'],
        'scope': value['scope'],
        'token_type': TokenTypeToJSON(value['tokenType']),
    };
}

