/* tslint:disable */
/* eslint-disable */
/**
 * OAuth Server
 * OIDC / OAuth 2.x server implementation
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TokenType = {
    Bearer: "Bearer",
    DpoP: "DPoP",
} as const;
export type TokenType = (typeof TokenType)[keyof typeof TokenType];

export function instanceOfTokenType(value: any): boolean {
    for (const key in TokenType) {
        if (Object.hasOwn(TokenType, key)) {
            if (TokenType[key as keyof typeof TokenType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TokenTypeFromJSON(json: any): TokenType {
    return TokenTypeFromJSONTyped(json, false);
}

export function TokenTypeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): TokenType {
    return json as TokenType;
}

export function TokenTypeToJSON(value?: TokenType | null): any {
    return value as any;
}

export function TokenTypeToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean,
): TokenType {
    return value as TokenType;
}
